# Generated by Django 3.1.3 on 2020-11-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendingmachine',
            options={'verbose_name': '자판기', 'verbose_name_plural': '자판기'},
        ),
        migrations.CreateModel(
            name='VendingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='상품명')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='수량')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.vendingmachine')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
            },
        ),
    ]
