# Generated by Django 3.1.3 on 2020-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0002_auto_20201112_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingitem',
            name='color',
            field=models.CharField(default='#ccc', max_length=30, verbose_name='색상'),
            preserve_default=False,
        ),
    ]
